name: MkDocs Preview (PR only)

on:
  pull_request:
    branches: [ mkdocs-example ]   # PRs targeting this branch
    paths:
      - "mkdocs.yml"
      - "docs/**"
      - ".github/workflows/mkdocs-preview.yml"
      # add any other paths your MkDocs demo uses

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-mkdocs-previews"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build --strict

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact (preview)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages (preview only)
        id: deployment
        uses: actions/deploy-pages@v4